name: Deply website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    -  name: Get latest code
       uses: actions/checkout@v2

    -  name: Sync files over FTP
       uses: SamKirkland/FTP-Deploy-Action@4.1.0
       with:
         server: ftp.worksper.com
         username: ${{ secrets.FTP_USER }}
         password: ${{ secrets.FTP_ PASSWORD }}
         server-dir: /
